name: BZN_Released_Managment_Workflow-Email

on:
  push:
    branches:
      - master
    paths:
      - 'Released/**'

jobs:
  send-release-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install 7-Zip & Node.js
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full
          npm init -y
          npm install nodemailer

      - name: Get today's date
        run: echo "TODAY_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Find all files in 'Released/' folder with current date
        id: dated_files
        run: |        
          MATCHED_FILE=$(find Released/ -type f -name "*${{ env.TODAY_DATE }}*" -printf "%T@ %p\n" \
              | sort -n | tail -1 | cut -d' ' -f2-)

          if [ -z "$MATCHED_FILE" ]; then
            echo "No files found with today's date: ${{ env.TODAY_DATE }}"
            exit 1
          fi

          echo "MATCHED_FILE=$MATCHED_FILE" >> $GITHUB_ENV

      - name: Set ZIP file name
        run: |
          FILE_BASE_NAME=$(basename "${{ env.MATCHED_FILE }}" .zip)
           echo "ZIP_NAME=$FILE_BASE_NAME" >> $GITHUB_ENV

      - name: Zip matched file
        run: |
          7z a -tzip -p${{ secrets.ZIP_PASSWORD }} -mem=ZipCrypto "${{ env.ZIP_NAME }}" "${{ env.MATCHED_FILE }}"

      - name: Send email via nodemailer
        env:
          SMTP_SERVER: smtp.rediffmailpro.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}
          EMAIL_SUBJECT: "Byzan Systems -: ${{ env.ZIP_NAME }}"
          EMAIL_BODY: |
                      Hello,

                      Please find attached update release zip file with password-protected (${{ env.ZIP_NAME }}).

                      Please use the password provided in a separate email to extract the contents.

                      Note: This is an automated email, please do not reply.

                      Regards,  
                      Byzan Release Management
          HELO_HOST: rediffmailpro.com
          IGNORE_CERT: true
        run: node BZN_Send_Email.js
